import { Talent, CastingCall, Testimonial, BlogItem } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All Categories', count: 24433, url:'/browse-talents' },
  { id: 'actors', name: 'Actors & Extras', count: 7931, icon: 'Clapperboard', url:'/browse-talents?category=Actors+%26+Extras' },
  { id: 'singers', name: 'Singers', count: 837, icon: 'Mic', url:'/browse-talents?category=Singers' },
  { id: 'dancers', name: 'Dancers', count: 1382, icon: 'Footprints',url:'/browse-talents?category=Dancers' },
  { id: 'models', name: 'Models', count: 8308, icon: 'Sparkles', url:'/browse-talents?category=Models' },
  { id: 'photographers', name: 'Photographers', count: 642, icon: 'Camera',url:'/browse-talents?category=Cinematographers+%2F+Videographers' },
  { id: 'directors', name: 'Directors & Crew', count: 424, icon: 'Film',url:'/browse-talents?category=Directors' },
  { id: 'promoters', name: 'Promoters & Hosts', count: 2802, icon: 'Megaphone',url:'/browse-talents?category=Promoters' },
  { id: 'makeup', name: 'Makeup & Hair Artists', count: 519, icon: 'Scissors',url:'/browse-talents?category=Makeup+%26+Hairstylists' },
  { id: 'voiceover', name: 'Voice Over Artists', count: 1588, icon: 'Volume2',url:'/browse-talents?category=MC%2FRJ%2FVJ%2FVoice+Over' },
];

export const LOCATIONS = [
  'All Locations',
  'Dubai, UAE',
  'Sharjah, UAE',
  'Abu Dhabi, UAE',
  'Riyadh, Saudi Arabia',
  'Jeddah, Saudi Arabia',
  'Doha, Qatar',
  'Manama, Bahrain',
];

export const REFRESH_YEARS = [2026, 2025, 2024, 2023];

export const INITIAL_TALENTS: Talent[] = [
  {
    id: 't1',
    name: 'Archana',
    gender: 'Female',
    categories: ['Models', 'Actors & Extras'],
    location: 'Sharjah, UAE',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=600',
    ],
    bio: 'Mode, fashion, luxury lifestyle, and fitness enthusiast. UAE national & international campaign veteran. Let us create cinematic magic together.',
    isPremium: true,
    stats: {
      height: 174,
      chestOrBust: 88,
      waist: 62,
      hips: 91,
      shoeSize: 39,
      eyeColor: 'Dark Brown',
      hairColor: 'Black',
      hairLength: 'Long',
    },
    experience: [
      'Lead Model: Bloomingdales Middle East Winter Campaign 2025',
      'Actor: UAE National Day Hero Film 2025',
      'Runway Model: Dubai Fashion Week Fall/Winter 2024',
    ],
  },
  {
    id: 't2',
    name: 'Faisal',
    gender: 'Male',
    categories: ['Actors & Extras', 'Models'],
    location: 'Dubai, UAE',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=600',
    ],
    bio: 'Fluent in Classical Arabic and English. Experienced in high-end luxury vehicle promos, television commercials, and traditional Gulf regional shoots.',
    isPremium: true,
    stats: {
      height: 187,
      chestOrBust: 102,
      waist: 81,
      hips: 100,
      shoeSize: 44,
      eyeColor: 'Hazel',
      hairColor: 'Dark Brown',
      hairLength: 'Short',
    },
    experience: [
      'Hero Talent: Emaar Properties Mega Project Reveal Video 2025',
      'Main Actor: Emirates Airline Global Business Class TVC',
      'Model: Saudi Aramco Heritage Campaign',
    ],
  },
  {
    id: 't3',
    name: 'Elena',
    gender: 'Female',
    categories: ['Models', 'Dancers'],
    location: 'Dubai, UAE',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=600',
    ],
    bio: 'Professional contemporary dancer and high-fashion model. Specialized in athletic modeling, cosmetics campaigns, and artistic screen staging.',
    isPremium: true,
    stats: {
      height: 178,
      chestOrBust: 84,
      waist: 59,
      hips: 89,
      shoeSize: 38,
      eyeColor: 'Green',
      hairColor: 'Auburn',
      hairLength: 'Medium',
    },
    experience: [
      'Soloist Dancer: Dubai Opera Contemporary Gala 2025',
      'Brand Ambassador: Sephora Middle East Summer Edit 2024',
      'Editorial Model: Harper’s Bazaar Arabia Portrait Feature',
    ],
  },
  {
    id: 't4',
    name: 'Kenji',
    gender: 'Male',
    categories: ['Models', 'Actors & Extras', 'Voice Over Artists'],
    location: 'Riyadh, Saudi Arabia',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=600',
    ],
    bio: 'Tokyo-born artist currently based in Riyadh. International look suitable for futuristic tech commercials, corporate branding, and narrative cinema.',
    isPremium: false,
    stats: {
      height: 182,
      chestOrBust: 96,
      waist: 76,
      hips: 94,
      shoeSize: 42,
      eyeColor: 'Dark Brown',
      hairColor: 'Silver-Dyed Black',
      hairLength: 'Short Curly',
    },
    experience: [
      'Principal Accent Voice: Neom City Future Living Expo Voiceover',
      'Talent: Hyundai Middle East SUV Launch Video',
    ],
  },
  {
    id: 't5',
    name: 'Yasmin',
    gender: 'Female',
    categories: ['Actors & Extras', 'Singers', 'Voice Over Artists'],
    location: 'Abu Dhabi, UAE',
    profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600',
    ],
    bio: 'Award-winning vocalist and screen actress. Able to perform in Gulf, Levantine, Egyptian dialects, and classic English. Warm, soulful jazz/pop range.',
    isPremium: true,
    stats: {
      height: 168,
      chestOrBust: 90,
      waist: 66,
      hips: 95,
      shoeSize: 37,
      eyeColor: 'Amber',
      hairColor: 'Dark Brown wavy',
      hairLength: 'Shoulder-Length',
    },
    experience: [
      'Featured Vocalist: Al Hosn Festival Opening Ceremony 2025',
      'Co-Lead Actress: MBC Narrative Drama Series 2024',
    ],
  },
  {
    id: 't6',
    name: 'Zayson',
    gender: 'Male',
    categories: ['Dancers', 'Actors & Extras', 'Promoters & Hosts'],
    location: 'Dubai, UAE',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600',
    ],
    bio: 'High-energy dancer, fitness model and event host. Extremely charismatic with extensive experience in luxury watch expos, athletic launches, and MC work.',
    isPremium: false,
    stats: {
      height: 190,
      chestOrBust: 108,
      waist: 84,
      hips: 102,
      shoeSize: 45,
      eyeColor: 'Blue-Gray',
      hairColor: 'Blonde Buzzcut',
      hairLength: 'Shaved',
    },
    experience: [
      'Official MC: Nike Middle East Run-Club Finals 2025',
      'Host: Dubai World Trade Center Luxury Expo Lounge',
    ],
  }
];

export const INITIAL_CASTINGS: CastingCall[] = [
  {
    id: 'c1',
    title: 'Multiple Roles For Global Commercial',
    client: 'Pandol Group',
    category: 'Actors & Extras',
    description: 'We are seeking multiple male and female talents of diverse Middle Eastern backgrounds for an upcoming flagship brand commercial. Roles range from lead family heads to young, upbeat tech commuters.',
    requirements: {
      gender: 'All',
      ageRange: '18 - 55 years old',
      languages: ['Arabic', 'English'],
      details: 'Must have natural acting expressions, comfortable in front of cinematic cameras. No spoken dialogue for extras, minor speaking roles for leads.',
    },
    location: 'Dubai, UAE',
    paymentType: 'Paid',
    rate: 'AED 2,000 - 3,500 / Day',
    expiryDate: '2026-07-15',
    shootDate: '2026-07-28',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=850',
    status: 'Open',
  },
  {
    id: 'c2',
    title: 'Females for Hair Product Digital Video',
    client: 'L‘Oréal Paris Middle East',
    category: 'Models',
    description: 'A global cosmetics brand is casting female promotional models with healthy, long, vibrant hair (natural brunette, auburn, or curls preferred) for their upcoming luxury hydration series.',
    requirements: {
      gender: 'Female',
      ageRange: '20 - 35 years old',
      languages: ['English'],
      details: 'Strictly looking for smooth, clean skin and long, well-maintained hair. Hair styling and conditioning are provided on set.',
    },
    location: 'Dubai, UAE',
    paymentType: 'Paid',
    rate: 'AED 4,500 / Day (Featured)',
    expiryDate: '2026-07-22',
    shootDate: '2026-08-01',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=850',
    status: 'Open',
  },
  {
    id: 'c3',
    title: 'Middle-Eastern Looking Males for Premium Hair Clay',
    client: 'Grooming Co. Riyadh',
    category: 'Models',
    description: 'Casting charismatic male actors with short to medium textured hair for a social media campaign featuring high-end clay and matte waxes.',
    requirements: {
      gender: 'Male',
      ageRange: '22 - 40 years old',
      languages: ['Arabic', 'English'],
      details: 'Must have sharp, groomed beards/mustaches, or be fully willing to shave depending on style direction. Confident, modern style is key.',
    },
    location: 'Riyadh, Saudi Arabia',
    paymentType: 'Paid',
    rate: 'SAR 3,000 / Flat Fee',
    expiryDate: '2026-07-30',
    shootDate: '2026-08-11',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=850',
    status: 'Open',
  },
  {
    id: 'c4',
    title: 'Contemporary Dancers for Immersive Expo Launch',
    client: 'Careem Promos',
    category: 'Dancers',
    description: 'Seeking synchronized dancers with background training in hip-hop, contemporary, or acrobatics to perform at a major smart-transportation reveal show in the Dubai Marina.',
    requirements: {
      gender: 'All',
      ageRange: '18 - 30 years old',
      languages: [],
      details: 'Requires excellent athletic stamina and rapid choreography adaptation. Must attend 3 full practice sessions prior to physical launch day (all paid).',
    },
    location: 'Dubai, UAE',
    paymentType: 'Paid',
    rate: 'AED 1,800 / Performance',
    expiryDate: '2026-07-10',
    shootDate: '2026-07-16',
    imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=850',
    status: 'Open',
  },
  {
    id: 'c5',
    title: 'Louvre Abu Dhabi Gallery Hostesses',
    client: 'Louvre Abu Dhabi (Cultural Event)',
    category: 'Promoters & Hosts',
    description: 'We are hiring premium hostesses and cultural ambassadors for the upcoming Summer Masterpieces Gala. Friendly, highly articulate, luxury hospitality experience is crucial.',
    requirements: {
      gender: 'Female',
      ageRange: '21 - 32 years old',
      languages: ['Arabic', 'French', 'English'],
      details: 'Extremely polite, elegant presentation, and interested in global arts. Uniforms provided by the museum organizers.',
    },
    location: 'Abu Dhabi, UAE',
    paymentType: 'Paid',
    rate: 'AED 12,000 / Gala Duration (4 Days)',
    expiryDate: '2026-07-18',
    shootDate: '2026-07-25',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=850',
    status: 'Open',
  },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test1',
    name: 'Baraa Rahmy',
    role: 'Fashion Model & Actor',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=300',
    rating: 5,
    quote: 'Yoocasta is hands down the absolute best! The projects I have been casted for are legendary, professional, and helped me secure my residency visa in Dubai. Extremely supportive team.',
    verified: true,
    project: 'Emaar Properties Promo',
  },
  {
    id: 'test2',
    name: 'Elnura Abdykasymova',
    role: 'Commercial Model',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    rating: 5,
    quote: 'The booking process was incredibly clear and honest. I booked the L‘Oréal hair commercial within my second week of registering! They pay exactly on time which is so rare in this industry.',
    verified: true,
    project: 'L‘Oréal Hair Commercial',
  },
  {
    id: 'test3',
    name: 'Evelina Alvarado',
    role: 'Hostess & Promoter',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
    rating: 5,
    quote: 'Being a premium member is so worth it. The priority application and premium casting alerts gave me 3 high-paid hosting jobs at Dubai World Trade Center this quarter alone!',
    verified: true,
    project: 'DWTC Luxury Expo 2026',
  }
];

export const CLIENT_PARTNERS = [
  { name: 'du', label: 'du Telecom' },
  { name: 'Brands For Less', label: 'Brands For Less' },
  { name: 'Quik', label: 'Careem Quik' },
  { name: 'Louvre Abu Dhabi', label: 'Louvre Abu Dhabi' },
  { name: 'Samana', label: 'Samana Developers' },
  { name: 'Himalaya Babycare', label: 'Himalaya' },
  { name: 'dubizzle', label: 'dubizzle' },
  { name: 'eon aligner', label: 'eon Aligner' },
  { name: 'YVOIRE', label: 'YVOIRE Beauty' },
  { name: 'Bee‘ah', label: 'Bee‘ah Environment' },
  { name: 'Al Ain Class', label: 'Al Ain Class Motors' },
  { name: 'Pride', label: 'Pride UAE' },
];

export const INITIAL_BLOGS: BlogItem[] = [
  {
    id: 'b1',
    title: 'How To Become A Top Fashion Model in Dubai',
    category: 'Advice & Tips',
    readTime: '5 min read',
    date: 'Jun 12, 2026',
    summary: 'The Middle Eastern fashion ecosystem is booming. Discover what directors look for when scouting models in Dubai, Abu Dhabi, and Riyadh.',
    imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=650',
    content: 'Dubai has firmly established itself as a global luxury fashion capital. Modeling in this region requires a unique combination of high adaptability, a professional portfolio (Comp card), and understanding regional sensitivities. To succeed: first, keep your measurements updated down to the millimeter. Second, build high-contrast neutral portfolio shots (minimal makeup, simple wear) before introducing stylized editorials. Join Yoocasta Premium to access private scouts.',
  },
  {
    id: 'b2',
    title: 'Starting a High-Paid Career as TV Host or Presenter',
    category: 'Industry Secrets',
    readTime: '4 min read',
    date: 'May 28, 2026',
    summary: 'From trade shows to sovereign promotional movies, the demand for bilingual corporate hosts has tripled. Learn how to prepare your video showreel.',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=650',
    content: 'Whether presenting details on smart automation at Gitex Dubai or introducing royalty at cultural functions, presenters are the voice of prestige. Having a crisp, versatile tone is your currency. If you are bilingual in Arabic and English, your rating and compensation automatically double. Ensure you host short dynamic intro videos and post them on your Yoocasta portfolio for direct booking.',
  },
  {
    id: 'b3',
    title: 'Top 5 Tips To Stand Out in Video Casting Submissions',
    category: 'Auditions',
    readTime: '3 min read',
    date: 'Apr 19, 2026',
    summary: 'First impressions on screen are instant. Read about lighting, background noise, and script delivery for remote submissions.',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=650',
    content: 'Directors filter casting submissions within 5 seconds. To stay in the running: 1. Film with natural face-on lighting (never background light!). 2. State your name, age, height, and location in a bubbly, confident tone during the intro. 3. Maintain silent pauses to let the director evaluate facial expression changes. Keep your audio crystal clear & free of echo.',
  },
];

export const FAQS = [
  {
    question: 'How do I submit my application for Casting Opportunities?',
    answer: 'Browse open casting calls on our dashboard, click on the card to see the full brief and rates, and click "Submit Application". Enter your registered email or profile link, upload a quick customized video or comment, and the casting team will instantly receive your comp card.',
  },
  {
    question: 'What is a Yoocasta Premium Membership and is it required?',
    answer: 'While basic profiles are free to create, our Premium Membership gives talents unlimited casting applications, priority visibility on director searches, a custom URL, and instant WhatsApp alerts for exclusive VIP campaigns. Standard premium is AED 20 per month.',
  },
  {
    question: 'How long does a booking confirmation take in the Middle East?',
    answer: 'Most commercial shoots and corporate events have short-turnarounds. After the casting team submits the shortlisted comp cards, brands usually finalize selection within 3 to 7 working days. If selected, our booking managers will contact you immediately via phone and WhatsApp.',
  },
  {
    question: 'I am a Brand or Director. How do I hire from Yoocasta?',
    answer: 'You can instantly publish a custom casting call by clicking "Post a Casting" on our header. Alternatively, reach out directly to management to access our advanced offline catalog and arrange private auditions at our Sharjah and Dubai partners.',
  },
];
